export const POKEMON_NAMES = [
  "bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon", "charizard",
  "squirtle", "wartortle", "blastoise", "caterpie", "metapod", "butterfree",
  "weedle", "kakuna", "beedrill", "pidgey", "pidgeotto", "pidgeot",
  "rattata", "raticate", "spearow", "fearow", "ekans", "arbok",
  "pikachu", "raichu", "sandshrew", "sandslash", "nidoran-f", "nidorina", "nidoqueen",
  "nidoran-m", "nidorino", "nidoking", "clefairy", "clefable", "vulpix", "ninetales",
  "jigglypuff", "wigglytuff", "zubat", "golbat", "oddish", "gloom", "vileplume",
  "paras", "parasect", "venonat", "venomoth", "diglett", "dugtrio",
  "meowth", "persian", "psyduck", "golduck", "mankey", "primeape",
  "growlithe", "arcanine", "poliwag", "poliwhirl", "poliwrath", "abra",
  "kadabra", "alakazam", "machop", "machoke", "machamp", "bellsprout",
  "weepinbell", "victreebel", "tentacool", "tentacruel", "geodude", "graveler",
  "golem", "ponyta", "rapidash", "slowpoke", "slowbro", "magnemite",
  "magneton", "farfetchd", "doduo", "dodrio", "seel", "dewgong",
  "grimer", "muk", "shellder", "cloyster", "gastly", "haunter",
  "gengar", "onix", "drowzee", "hypno", "krabby", "kingler",
  "voltorb", "electrode", "exeggcute", "exeggutor", "cubone", "marowak",
  "hitmonlee", "hitmonchan", "lickitung", "koffing", "weezing", "rhyhorn",
  "rhydon", "chansey", "tangela", "kangaskhan", "horsea", "seadra",
  "goldeen", "seaking", "staryu", "starmie", "mr-mime", "scyther",
  "jynx", "electabuzz", "magmar", "pinsir", "tauros", "magikarp",
  "gyarados", "lapras", "ditto", "eevee", "vaporeon", "jolteon",
  "flareon", "porygon", "omanyte", "omastar", "kabuto", "kabutops",
  "aerodactyl", "snorlax", "articuno", "zapdos", "moltres", "dratini",
  "dragonair", "dragonite", "mewtwo", "mew",
  "chikorita", "bayleef", "meganium", "cyndaquil", "quilava", "typhlosion",
  "totodile", "croconaw", "feraligatr", "sentret", "furret", "hoothoot",
  "noctowl", "ledyba", "ledian", "spinarak", "ariados", "crobat",
  "chinchou", "lanturn", "pichu", "cleffa", "igglybuff", "togepi",
  "togetic", "tyrogue", "hitmontop", "smooth", "politoed", "espeon",
  "umbreon", "murkrow", "slowking", "misdreavus", "wooper", "girafarig",
  "pineco", "forretress", "dunsparce", "snubbull", "granbull", "qwilfish",
  "scizor", "shuckle", "heracross", "sneasel", "teddiursa", "ursaring",
  "slugma", "magcargo", "swinub", "piloswine", "corsola", "remoraid",
  "octillery", "mantine", "skarmory", "houndour", "houndoom", "kingdra",
  "phanpy", "donphan", "porygon2", "steelix", "smoochum", "elekid",
  "magby", "miltank", "raikou", "entei", "suicune", "larvitar",
  "pupitar", "tyranitar", "lugia", "ho-oh", "celebi",
  "treecko", "grovyle", "sceptile", "torchic", "combusken", "blaziken",
  "mudkip", "marshtomp", "swampert", "poochyena", "mightyena", "zigzagoon",
  "linoone", "taillow", "swellow", "wingull", "pelipper", "ralts",
  "kirlia", "gardevoir", "surskit", "masquerain", "shroomish", "breloom",
  "slakoth", "vigoroth", "slaking", "nincada", "ninjask", "shedinja",
  "whismur", "loudred", "exploud", "skitty", "delcatty", "spinda",
  "zangoose", "castform", "kecleon", "shuppet", "banette", "duskull",
  "dusclops", "trapinch", "vibrava", "flygon", "cacnea", "cacturne",
  "swablu", "altaria", "seviper", "lunatone", "solrock", "barboach",
  "whiscash", "corphish", "crawdaunt", "baltoy", "claydol", "lileep",
  "cradily", "anorith", "armaldo", "feebas", "milotic", "chimecho",
  "absol", "wynaut", "snorunt", "glalie", "spheal", "sealeo",
  "walrein", "clamperl", "huntail", "gorebyss", "relicanth", "luvdisc",
  "bagon", "shelgon", "salamence", "beldum", "metang", "metagross",
  "regirock", "regice", "registeel", "latias", "latios", "kyogre",
  "groudon", "rayquaza", "jirachi", "deoxys",
  "turtwig", "grotle", "torterra", "chimchar", "monferno", "infernape",
  "piplup", "prinplup", "empoleon", "starly", "staravia", "staraptor",
  "bidoof", "bibarel", "buizel", "floatzel", "cherubi", "cherrim",
  "shellos", "gastrodon", "cranidos", "rampardos", "shieldon", "bastionage",
  "burmy", "wormadam", "mothim", "combee", "vespiquen", "pachirisu",
  "buneary", "lopunny", "glameow", "purugly", "chatot", "spiritomb",
  "gible", "gabite", "garchomp", "munchlax", "riolu", "lucario",
  "hippopotas", "hippowdon", "skorupi", "drapion", "carnivine",
  "snover", "abomasnow", "weavile", "magnezone", "lickilicky",
  "rhyperior", "tangrowth", "electivire", "magmortar", "togekiss", "yanmega",
  "leafeon", "glaceon", "gliscor", "mamoswine", "porygon-z", "gallade",
  "probopass", "dusknoir", "froslass", "rotom", "uxie", "mesprit",
  "azelf", "dialga", "palkia", "heatran", "regigigas", "giratina",
  "cresselia", "phione", "manaphy", "darkrai", "shaymin", "arceus",
  "snivy", "servine", "serperior", "tepig", "pignite", "emboar",
  "oshawott", "dewott", "samurott", "patrat", "watchog", "lillipup",
  "herdier", "stoutland", "pidove", "tranquill", "unfezant", "blitzle",
  "zebstrika", "roggenrola", "boldore", "gigalith", "woobat", "swoobat",
  "drilbur", "excadrill", "audino", "timburr", "gurdurr", "conkeldurr",
  "tympole", "palpitoad", "seismitoad", "throh", "sawk", "sewaddle",
  "swadloon", "leavanny", "venipede", "whirlipede", "scolipede", "cottonee",
  "whimscott", "petilil", "lilligant", "basculin", "ducklett", "swanna",
  "vanillite", "vanillish", "vanilluxe", "deerling", "sawsbuck", "emolga",
  "joltik", "galvantula", "ferroseed", "ferrothorn", "klink", "klang",
  "klinklang", "tynamo", "eelektrik", "eelektross", "elgyem", "beheeyem",
  "litwick", "lampent", "chandelure", "axew", "fraxure", "haxorus",
  "cubchoo", "beartic", "cryogonal", "shelmet", "accelgor", "stunfisk",
  "mienfoo", "mienshao", "druddigon", "golett", "golurk", "pawniard",
  "bisharp", "bouffalant", "rufflet", "braviary", "vullaby", "mandibuzz",
  "heatmor", "durant", "deino", "zweilous", "hydreigon", "larvesta",
  "volcarona", "cobalion", "terrakion", "virizion", "tornadus", "thundurus",
  "reshiram", "zekrom", "landorus", "kyurem", "victini", "keldeo",
  "meloetta", "genesect",
  "chespin", "quilladin", "chesnaught", "fennekin", "braixen", "delphox",
  "froakie", "frogadier", "greninja", "bunnelby", "diggersby", "fletchling",
  "fletchinder", "talonflame", "scatterbug", "spewpa", "vivillon", "litleo",
  "pyroar", "flabebe", "floette", "florges", "skiddo", "gogoat",
  "pancham", "pangoro", "furfrou", "espurr", "meowstic", "honedge",
  "doublade", "aegislash", "spritzee", "aromatisse", "swirlix", "slurpuff",
  "inkay", "malamar", "binacle", "barbaracle", "helioptile", "heliolisk",
  "tyrunt", "tyrantrum", "amaura", "aurorus", "sylveon", "carbink",
  "goomy", "sliggoo", "goodra", "klefki", "phantump", "trevenant",
  "pumpkaboo", "gourgeist", "bergmite", "avalugg", "noibat", "noivern",
  "xerneas", "yveltal", "zygarde", "diancie", "hoopa", "volcanion",
  "rowlet", "dartrix", "decidueye", "litten", "torracat", "incineroar",
  "popplio", "brionne", "primarina", "pikipek", "trumbeak", "toucannon",
  "yungoos", "gumshoos", "grubbin", "charjabug", "vikavolt", "crabrawler",
  "crabominable", "cutiefly", "ribombee", "rockruff", "lycanroc", "wishiwashi",
  "mareanie", "toxapex", "mudbray", "mudsdale", "dewpider", "araquanid",
  "fomantis", "lurantis", "morelull", "shiinotic", "salandit", "salazzle",
  "stufful", "bewear", "bounsweet", "steenee", "tsareena", "comfey",
  "oranguru", "passimian", "wimpod", "golisopod", "sandygast", "palossand",
  "pyukumuku", "type-null", "silvally", "minior", "komala", "togedemaru",
  "mimikyu", "bruxish", "drampa", "dhelmise", "jangmo-o", "hakamo-o",
  "kommo-o", "tapu-koko", "tapu-lele", "tapu-bulu", "tapu-fini", "cosmog",
  "cosmoem", "solgaleo", "lunala", "nihilego", "buzzwole", "pheromosa",
  "xurkitree", "celesteela", "kartana", "guzzlord", "necrozma", "magearna",
  "marshadow", "poipole", "naganadel", "stakataka", "blacephalon", "zeraora",
  "meltan", "melmetal",
  "grookey", "thwackey", "rillaboom", "scorbunny", "raboot", "cinderace",
  "sobble", "drizzile", "inteleon", "skwovet", "greedent", "rookidee",
  "corvisquire", "corviknight", "blipbug", "dottler", "orbeetle", "wooloo",
  "dubwool", "chewtle", "drednaw", "yamper", "boltund", "rolycoly",
  "carkol", "coalossal", "applin", "flapple", "appletun", "silicobra",
  "sandaconda", "cramorant", "arrokuda", "barraskewda", "toxel", "toxtricity",
  "sizzlipede", "centiskorch", "clobbopus", "grapploct", "sinistea", "polteageist",
  "cursola", "dracozolt", "arctozolt", "dracovish", "arctovish", "duraludon",
  "dreepy", "drakloak", "dragapult", "zacian", "zamazenta", "eternatus",
  "kubfu", "urshifu", "zarude", "regieleki", "regidrago", "glastrier",
  "spectrier", "calyrex", "wyrdeer", "kleavor", "ursaluna", "basculegion",
  "sneasler", "overqwil", "enamorus", "pecharunt",
  "sprigatito", "floragato", "meowscarada", "fuecoco", "crocalor", "skeledirge",
  "quaxly", "quaxwell", "quaquaval", "lechonk", "oinkologne", "tarountula",
  "spidops", "nymble", "lokix", "pawmi", "pawmo", "pawmot",
  "tandemaus", "maushold", "fidough", "dachsbun", "bombirdier", "squawkabilly",
  "flamigo", "cetoddle", "cetitan", "wiglett", "wugtrio", "naclstack",
  "rabsca", "flittle", "espathra", "tinkatink", "tinkatuff", "tinkaton",
  "ironbundle", "varoom", "revavroom", "cyclizar", "scream-tail", "roaring-moon",
  "iron-seaking", "frigibax", "arctibax", "baxcalibur", "gimmighoul", "gholdengo",
  "wo-chien", "chien-pao", "ting-lu", "chi-yu", "koraidon", "miraidon",
  "walking-wake", "iron-leaves", "pecharunt"
]
